### PR TITLE
Jkilloran: Protect Lu Apps for ill behaving individual Process instance

### PR DESCRIPTION
**Pull request by jrkilloran**
Harden lu Processes so that even panics on individual instances do not cause the app to exit. Retry on most errors except where nil, context cancelled or a break loop was returned.

### CODE REVIEW

**Comment by adamhicks** [comment]
> Harden lu Processes so that even panics on individual instances do not cause the app to exit. Retry on most errors except where nil, context cancelled or a break loop was returned.

It is a design choice to terminate the app if a process errors and we have process wrappers which insulate processes where errors can be tolerated. The wrapContextLoop is designed to insulate the processes where we want to log errors and restart. I don't want to make every process to behave this way.

I value panics and the stack traces they produce, this change simplifies and obscures the panic, I don't think this is an improvement.

This change is making a lot of core changes to lu, if you want to make these changes I suggest that we talk about each problem and tackle them individually.

**Comment by jrkilloran** [comment]
Made monitoring optional and not on by default (also allowed individual overrides at the Process level itself). However to answer you question about wrapContextLoop that works fine where the process function has been created with that "wrapping" it but Process is a open struct that can be populated with anything you want directly so unless the App/Process setup itself has a simple mechanism to stop abending of a Process bringing down the whole App then it will be a problem waiting to happen especially given open sourcing the framework introduces use that are not within our knowledge/control. To answer the general question though given how much important services like Identity are relied on by the remainder of the services having them fail fast is not a pattern that works in the cases where bringing down an entire service has wider effects and were potentially the break will continue in a poison pill fashion. However I accept that also being able to fail fast is the best case for some services where we want new instances to take over and recovery itself is too expensive.

**Comment by neilgarb** [comment]
> It is a design choice to terminate the app if a process errors and we have process wrappers which insulate processes where errors can be tolerated. The wrapContextLoop is designed to insulate the processes where we want to log errors and restart. I don't want to make every process to behave this way.
>
> I value panics and the stack traces they produce, this change simplifies and obscures the panic, I don't think this is an improvement.

I think the design choice is sound, and if we're careful with the helpers that we build, this shouldn't be a problem. Panics are another story, though. If a process panics the whole app will crash, and in that case it would be useful to have a way to recover (while maintaining all the useful logs and other such things.) We do need some protection against that.

**Comment by adamhicks** [comment]
I appreciate the feedback.
On the topic of errors from processes, I think we can provide sufficient protection for users of the package without adding this complication to the App, i.e. by providing Processes that don't return errors.

For panics, can we try out a ProcessFunc wrapper that protects against panics, maybe something like:
```
func Recoverable(f lu.ProcessFunc) lu.ProcessFunc {
   ...
```
which can then be used with other processes and then can be moved to a process.Option.

**Comment by jrkilloran** [comment]
Okay so made the hardening optional on the App and also enable-able on a Process by Process basis; changed the naming a little from using **monitor** as the noun/verb to **recover** (which feels better); so the default behaviour is now fail fast as it has always been but we now also cater to the cases where recovery is the required/correct way to go. So why is the recovery code still in the App, well a few reasons:
-  Its basically the only way to have it ensure we can run every process in a hardened manner so protecting the App from ill behaving processes
- We've open sourced the lib so we open out the pool of users for whom it might be useful
- Process is a struct and not an interface, so nothing stopping someone doing their own ProcessFunc implementations and thus we cannot just rely on a ContextLoop for example
- It actually feels like the right place since the rest of the error handling code (Groups, Shutdown etc) is in App and it significantly lowers the entry level to enabling the behaviour
- It was a simple error that took down Identity, and continued to take it down, not a Panic (though they have occurred elsewhere). So one size does not necessarily fit all and my significant experience is the simpler your recovery solution is to enable/operate, the more visible it is, the less coding/observation/review it takes to ensure it covers new code the less likely you are to be woken at 4am.

**Comment by adamhicks** [comment]
I want to keep the idea that processes must return nil when they are done, and they won't be restarted.

I don't want to add these complications in to the already complex App. I want to keep lu focused and clean, adding more options right now dilutes that idea.

If you want to explore recovering from panics in processes, can you please create a new MR that does so in the process package.

**Comment by jrkilloran** [comment]
Just to follow on one bit of misunderstanding above - if a process returned nil even with the recovery turned on it would still exit because return nil does not exit the App unless it is the very last process - the only thing the recovery retries would be ab-ends with errors and even then if the process does actually panic it would just log the panic and terminate the process with a nil result so it does not terminate the app.

**Pull request closed without merging**
